#!/usr/bin/env bash

ENV_PATH=/home/ubuntu/jonghun/.env

echo "MONGO_USER=${MONGO_USER}" >> $ENV_PATH
echo "MONGO_PASS=${MONGO_PASS}" >> $ENV_PATH
echo "SECRET_KEY=${SECRET_KEY}" >> $ENV_PATH
echo "FLASK_SECRET_KEY=${FLASK_SECRET_KEY}" >> $ENV_PATH
echo "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}" >> $ENV_PATH
echo "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}" >> $ENV_PATH
echo "KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}" >> $ENV_PATH
echo "AWS_S3IMAGE_ACCESS_KEY_ID=${AWS_S3IMAGE_ACCESS_KEY_ID}" >> $ENV_PATH
echo "AWS_S3IMAGE_SECERT_ACCESS_KEY=${AWS_S3IMAGE_SECERT_ACCESS_KEY}" >> $ENV_PATH