name: Build and Deploy Flask to AWS EC2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_NAME: jonghun_project
  BUCKET_NAME: jonghun-cicd-bucket
  CODE_DEPLOY_APP_NAME: jonghun_cicd
  DEPLOYMENT_GROUP_NAME: jonghun_instance
  MONGO_USER: ${{ secrets.MONGO_USER }}
  MONGO_PASS: ${{ secrets.MONGO_PASS }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install Python and pip
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Make Zip File
        run: |
          . venv/bin/activate
          zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: List Zip File Contents
        run: |
          unzip -l $GITHUB_SHA.zip

      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment 
                --application-name $CODE_DEPLOY_APP_NAME 
                --deployment-config-name CodeDeployDefault.AllAtOnce
                --deployment-group-name $DEPLOYMENT_GROUP_NAME 
                --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
                --environment-variables-overrides key=MONGO_USER,value=$MONGO_USER key=MONGO_PASS,value=$MONGO_PASS key=SECRET_KEY,value=$SECRET_KEY key=FLASK_SECRET_KEY,value=$FLASK_SECRET_KEY key=GOOGLE_CLIENT_ID,value=$GOOGLE_CLIENT_ID key=GOOGLE_CLIENT_SECRET,value=$GOOGLE_CLIENT_SECRET key=KAKAO_CLIENT_ID,value=$KAKAO_CLIENT_ID key=AWS_S3IMAGE_ACCESS_KEY_ID,value=$AWS_S3IMAGE_ACCESS_KEY_ID key=AWS_S3IMAGE_SECERT_ACCESS_KEY,value=$AWS_S3IMAGE_SECERT_ACCESS_KEY
